-----INSERTS EN PAIS---------------
INSERT INTO PAIS(PAIS_ID,PAIS)VALUES(incremento_pais.nextval,'COSTA RICA');
INSERT INTO PAIS(PAIS_ID,PAIS)VALUES(incremento_pais.nextval,'PANAMA');
INSERT INTO PAIS(PAIS_ID,PAIS)VALUES(incremento_pais.nextval,'NICARAGUA');
INSERT INTO PAIS(PAIS_ID,PAIS)VALUES(incremento_pais.nextval,'COLOMBIA');
INSERT INTO PAIS(PAIS_ID,PAIS)VALUES(incremento_pais.nextval,'VENEZUELA');
------------EL SELECT ES PARA QUE VEAN CON CUAL ID QUEDO COSTA RICA
------------EN MI CASO FUE EL ID 2.
SELECT * FROM PAIS;
-------------INSERTS EN PROVINCIA------------
INSERT INTO PROVINCIA (PROVINCIA_ID,PROVINCIA,PAIS_ID)VALUES(incremento_provincia.nextval,'SAN JOSÉ',2);
INSERT INTO PROVINCIA (PROVINCIA_ID,PROVINCIA,PAIS_ID)VALUES(incremento_provincia.nextval,'PUNTARENAS',2);
INSERT INTO PROVINCIA (PROVINCIA_ID,PROVINCIA,PAIS_ID)VALUES(incremento_provincia.nextval,'ALAJUELA',2);
INSERT INTO PROVINCIA (PROVINCIA_ID,PROVINCIA,PAIS_ID)VALUES(incremento_provincia.nextval,'LIMÓN',2);
INSERT INTO PROVINCIA (PROVINCIA_ID,PROVINCIA,PAIS_ID)VALUES(incremento_provincia.nextval,'GUANACASTE',2);
INSERT INTO PROVINCIA (PROVINCIA_ID,PROVINCIA,PAIS_ID)VALUES(incremento_provincia.nextval,'CARTAGO',2);
INSERT INTO PROVINCIA (PROVINCIA_ID,PROVINCIA,PAIS_ID)VALUES(incremento_provincia.nextval,'HEREDIAÉ',2);
-------------SELECT PARA VER LOS ID
SELECT * FROM PROVINCIA;
------------INSERTS EN CANTONES
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'ESCAZÚ',2);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'DESAMPARADOS',2);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'ALAJUELITA',2);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'ESPARZA',3);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'GOLFITO',3);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'GARABITO',3);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'GRECIA',4);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'GUATUSO',4);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'OROTINA',4);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'MATINA',5);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'POCOCI',5);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'SIQUIRRES',5);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'LIBERIA',6);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'HOJANCHA',6);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'ABANGARES',6);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'EL GUARCO',7);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'TURRIALBA',7);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'OREAMUNO',7);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'BARVA',8);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'SANTO DOMINGO',8);
INSERT INTO CANTON (CANTON_ID,CANTON,PROVINCIA_ID) VALUES(incremento_canton.nextval,'SAN RAFAEL',8);
-------------SELECT PARA VER LOS ID
SELECT * FROM CANTON;
-------------INSERTS EN DISTRITO
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN ANTONIO',2);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN RAFAEL',2);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN  MIGUEL',2);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN JUAN DE DIOS',3);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'LOS GUIDO',3);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'PATARRÁ',3);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN JOCESITO',4);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'CONCEPCIÓN',4);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN FELIPE',4);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'ESPIRITU SANTO',5);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN JERÓNIMO',5);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'MACACONA',5);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'GOLFITO',6);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'PUERTO JIMENEZ',6);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'PAVÓN',6);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'JACÓ',7);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'TÁRCOLES',7);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'GRECIA',8);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN ISIDRO',8);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'RÍO CUARTO',8);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN RAFAEL',9);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'BUENA VISTA',9);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'COTE',9);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'OROTINA',10);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'HACIENDA VIEJA',10);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'COYOLAR',10);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'MATINA',11);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'BATÁN',11);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'CARRANDI',11);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'GUÁPILES',12);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'JIMÉNEZ',12);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'ROXANA',12);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SIQUIRRES',13);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'PACUARITO',13);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'FLORIDA',13);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'CAÑAS DULCES',14);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'NACASCOLO',14);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'MAYORGA',14);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'MONTE ROMO',15);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'PUERTO CARRILLO',15);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'HUACAS',15);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'LAS JUNTAS',16);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SIERRA',16);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN JUAN',16);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'EL TEJAR',17);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN ISIDRO',17);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'TOBOSI',17);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'TURRIALBA',18);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'LA SUIZA',18);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'PERALTA',18);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN RAFAEL',19);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'CIPRESES',19);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SANTA ROSA',19);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'BARVA',20);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN PEDRO',20);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN PABLO',20);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SANTO DOMINGO',21);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN VICENTE',21);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN MIGUEL',21);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN RAFAEL',22);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SAN JOSECITO',22);
INSERT INTO DISTRITO (DISTRITO_ID,DISTRITO,CANTON_ID) VALUES (incremento_distrito.nextval,'SANTIAGO',22);
-------------SELECT PARA VER LOS ID
SELECT * FROM DISTRITO;





  
